Fix mainnet-public monitor alerts (#4405)
* Add a configurable API timeout property and reduce it from 60s to 30s by default
* Add run ID to logs to trace concurrent executions
* Change retry max attempts from 10 to 2
* Change retry backoff from 50ms to 1s
* Change retry to retry 5xx status in addition to 429
* Fix retries exhausted not throwing an error
* Fix JSON response fields not ordered alphabetically
* Fix not logging configuration to stdout
* Fix TypeError: Cannot read properties of undefined (reading 'numPassedTests') for /api/v1/status/:name with non-existing name
* Fix TypeError: singleTransactions.filter is not a function
* Fix uncaught errors due to race condition in async behavior
* Remove brittle pid tracking in favor of a running flag on each server

Signed-off-by: Steven Sheehy <steven.sheehy@swirldslabs.com>