Add grpc inprocess dependency in hedera-mirror-test project (#7112)
Upon upgrading to gRPC version 1.58.0, a NoClassDefFoundError for io.grpc.inprocess.InProcessChannelBuilder was encountered, causing a BeanCreationException when initializing SDKClient in the hedera-mirror-test project.
Adding testImplementation("io.grpc:grpc-inprocess") to the Gradle build file resolved the issue.

Signed-off-by: Yordan Iliev <yordan.iliev@limechain.tech>