Add NotifyingTopicListener Support for Citus w PG 14 (#2771)
When updating to citus for the v2 database the `NotifyingTopicListener` flow seemed to not be supported when using PG 14 as the underlying db.
It continuously hit an exception unable to find the `ScramException.class` in the classPath.
```
Unhandled exception java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/ongres/scram/common/exception/ScramException
```

Vertx provides integration with the [SASL SCRAM-SHA-256 authentication mechanism](https://vertx.io/docs/4.1.5/vertx-pg-client/java/#_sasl_scram_sha_256_authentication_mechanism) that we were not utilizing.

- Add `com.ongres.scram: client` dependency to grpc `pom.xml` to ensure `ScramException.class` can be found in the classPath
- Update `DbProperties` with `sslMode` config, default to `SslMode.DISABLE`
- Update `NotifyingTopicListener` with support to set SslMode configuration.
- Update `vertx` dependency to `4.2.0` from `4.1.5`
- Replace deprecated reactor `EmitterProcessor` with `Sinks.many().multicast()`
- Update citus images from `10.2.2-alpine` to `10.2.2-alpine`
- Replace deprecated jackson `PropertyNamingStrategy` with `PropertyNamingStrategies` in `NotifyingTopicListener` 

Signed-off-by: Nana-EC <nana.essilfie-conduah@hedera.com>