Fix NoClassDefFoundError in RecordFileParser (0.70) (#4980)
* Add temporary volume to importer pod so it can load native libraries
* Fix loading current block as last block on startup
* Fix parser not retrying java.lang.Error
* Fix parser not validating hash chain

Signed-off-by: Steven Sheehy <steven.sheehy@swirldslabs.com>