Rename CustomCallOperation  (#9782)
Currently when trying to run transaction using Reusables services transactionExecutor
we are getting the following error -

java.lang.RuntimeException: java.lang.NoSuchMethodError: 'void com.hedera.node.app.service.contract.impl.exec.operations.CustomCallOperation.<init>(com.hedera.node.app.service.contract.impl.exec.FeatureFlags, org.hyperledger.besu.evm.gascalculator.GasCalculator, com.hedera.node.app.service.contract.impl.exec.AddressChecks)'

Services CustomCallOperation clashes with our CustomCallOperation.java causing the issue.
Renaming our CustomCallOperation to HederaCustomCallOperation similar to the other custom operations that we have fixes the conflict.

This PR modifies
Rename CustomCallOperation to HederaCustomCallOperation

Signed-off-by: Kristiyan Selveliev <kristiyan.selveliev@limechain.tech>